processing_states:
  Idle: 0
  EyeWarmupDesc: 1
  EyeWarmupBlink: 2
  EyeWarmupText: 3
  EyeWarmupMove: 4
  Background: 5
  Inference: 6

logical_groups:
  EYE_MOVEMENT: 1
  BACKGROUND: 2
  INFERENCE: 3

event_ids:
  EYE_WARMUP_DESC: -1
  EYE_WARMUP_BLINK: 10
  EYE_WARMUP_TEXT: 11
  EYE_WARMUP_MOVE: 12
  BACKGROUND: 1
  TASK_PERIOD: 10

states:
  Idle:
    accepted_events:
      EYE_WARMUP_DESC: EyeWarmupDesc
      BACKGROUND: Background
      TASK_PERIOD: Inference
  EyeWarmupDesc:
    accepted_events:
      EYE_WARMUP_BLINK: EyeWarmupBlink
      BACKGROUND: Background
  EyeWarmupBlink:
    accepted_events:
      EYE_WARMUP_TEXT: EyeWarmupText
      BACKGROUND: Background
      EYE_WARMUP_BLINK: EyeWarmupBlink
    data_collection_group: EYE_MOVEMENT
  EyeWarmupText:
    accepted_events:
      EYE_WARMUP_MOVE: EyeWarmupMove
      BACKGROUND: Background
  EyeWarmupMove:
    accepted_events:
      EYE_WARMUP_BLINK: EyeWarmupBlink
      EYE_WARMUP_TEXT: EyeWarmupText
      BACKGROUND: Background
    data_collection_group: EYE_MOVEMENT
    on_transition_actions:
      Background: [FIT]
    on_transition_action_groups:
      Background:
        FIT: EYE_MOVEMENT
  Background:
    accepted_events:
      TASK_PERIOD: Inference
    data_collection_group: BACKGROUND
    on_exit_actions: [FIT]
  Inference:
    accepted_events:
      EYE_WARMUP_DESC: EyeWarmupDesc
      BACKGROUND: Background
    data_collection_group: INFERENCE
    on_entry_actions: [PREDICT, PARTIAL_FIT]
    on_exit_actions: [PREDICT, PARTIAL_FIT]
    on_entry_action_groups:
      PREDICT: INFERENCE
      PARTIAL_FIT: INFERENCE
    on_exit_action_groups:
      PREDICT: INFERENCE
      PARTIAL_FIT: INFERENCE
