processing_states:
  Idle: 0
  Idle2: -1
  EyeWarmupDesc: 1
  EyeWarmupBlink: 2
  EyeWarmupText: 3
  EyeWarmupMove: 4
  Background: 5
  Rest: 6
  Imagery: 7

logical_groups:
  REST: 0
  IMAGERY: 1
  EYE_MOVEMENT: 2
  BACKGROUND: 3

event_ids:
  EYE_WARMUP_DESC: 0
  EYE_WARMUP_BLINK: 10
  EYE_WARMUP_TEXT: 11
  EYE_WARMUP_MOVE: 12
  BACKGROUND: 1
  REST: 2
  ATTENTION: 3
  POINT: 5
  VAS: 0
  IMAGE_LEFT: 5
  IMAGE_RIGHT: 4

windowing:
  window_size: 1500
  step_sizes:
    PARTIAL_FIT: 1500
    COLLECT_FOR_TRAIN: 1500
    PREDICT: 1500

states:
  Idle:
    accepted_events:
      EYE_WARMUP_DESC: EyeWarmupDesc
      EYE_WARMUP_BLINK: EyeWarmupBlink

  Idle2:
    accepted_events:
      POINT: Imagery
      REST: Rest
      VAS: Idle2
      IMAGE_LEFT: Imagery
      IMAGE_RIGHT: Imagery
      BACKGROUND: Idle2

  EyeWarmupDesc:
    accepted_events:
      EYE_WARMUP_BLINK: EyeWarmupBlink
      BACKGROUND: Background

  EyeWarmupBlink:
    accepted_events:
      EYE_WARMUP_TEXT: EyeWarmupText
      BACKGROUND: Background
      EYE_WARMUP_BLINK: EyeWarmupBlink
    data_collection_group: EYE_MOVEMENT
    on_transition_actions:
      Background:
        - name: FIT
          group: EYE_MOVEMENT

  EyeWarmupText:
    accepted_events:
      EYE_WARMUP_MOVE: EyeWarmupMove
      BACKGROUND: Background

  EyeWarmupMove:
    accepted_events:
      EYE_WARMUP_BLINK: EyeWarmupBlink
      EYE_WARMUP_TEXT: EyeWarmupText
      BACKGROUND: Background
    data_collection_group: EYE_MOVEMENT
    on_transition_actions:
      Background:
        - name: FIT
          group: EYE_MOVEMENT

  Background:
    accepted_events:
      REST: Rest
      EYE_WARMUP_DESC: EyeWarmupDesc
      IMAGE_LEFT: Imagery
      IMAGE_RIGHT: Imagery
      POINT: Imagery
    data_collection_group: BACKGROUND
    on_exit_actions:
      - name: FIT
        group: BACKGROUND

  Rest:
    accepted_events:
      IMAGE_LEFT: Imagery
      IMAGE_RIGHT: Imagery
      POINT: Imagery
      BACKGROUND: Background
      ATTENTION: Idle2
    data_collection_group: REST
    on_entry_actions:
      - name: COLLECT_FOR_TRAIN
        group: REST
      - name: PREDICT
        group: REST
    on_exit_actions:
      - name: COLLECT_FOR_TRAIN
        group: REST
      - name: PREDICT
        group: REST

  Imagery:
    accepted_events:
      REST: Rest
      VAS: Idle2
      BACKGROUND: Idle2
    data_collection_group: IMAGERY
    on_exit_actions:
      - name: COLLECT_FOR_TRAIN
        group: IMAGERY
      - name: PREDICT
        group: IMAGERY
    on_entry_actions:
      - name: COLLECT_FOR_TRAIN
        group: IMAGERY
      - name: PREDICT
        group: IMAGERY
    class_label: 1
